backend/app/now.js, backend/template.yaml, src/store/api.js, src/store/data_layer/data_store.js
Alright, I'm opening this pull-request because _I think_ this should fix issue #119.  I've organized this PR into three parts so hopefully that will make it easier to review my code.
Foremost, this pull requests seeks to fix two issues raised by #119:
1. The cache size was exceeding localStorage's capacity
2. The dashboard was making extraneous requests for data that did not exist:
For instance, if you load up [Arnold Hall](https://dashboard.sustainability.oregonstate.edu/#/building/14/2) in the console you'll notice it is always `GET` requesting the interval between `1613213100` & `1613222100` (time between 2:45 AM & 5:15 AM on February 13th).  From what I can tell by directly querying for this interval on SQL-workbench, it seems this data just does not exist, I just get a bunch of …
=> Switched Localstorage cache to use IndexedDB API

src/store/data_layer/data_store.js
This is a really short one-line fix to one of the errors which occurred yesterday when the system didn't fall back to the locale `Date.now()` timestamp.  It looks kinda useless but without the empty catch statement the API request will throw an error out and therefore halt the rest of the cache queries (as we saw yesterday).
=> bugfix for remote systemtime fail

src/components/view/card.vue
This is a PR to resolve issue #132. This PR provides next/previous arrows to the charts in order to scroll through them easily.  The only modified file is `card.vue`. 
Here's a gif of the current arrows functioning: ![animated image of arrow buttons](https://raw.githubusercontent.com/MilanDonhowe/ReadmeImages/master/ArrowButtonsDashboard.gif)
Since this is a UI change I'll likely need feedback and approval from Brandon & Lety for the change but I wanted to have this PR up in order for code review / documentation purposes.
=> Add chart arrows#132

src/components/view/card.vue
Right now the axis of the graphs from the buildings tab dip [below the lower card border ](https://dashboard.sustainability.oregonstate.edu/#/building/16/2)and this fixes that issue by adding additional padding to the bottom of the card div container.
=> Fix card graph padding

src/components/building_list/building_list.vue, src/components/view/view.vue
Now the linked full-view graphs of Solar panels will only show interval ticks of hours or minutes (otherwise chartJS will produce a constant horizontal trend-line since our default unit is Energy in Interval which will always average to zero).
=> Refactored range difference check for solar panels

backend/app/building.js, backend/template.yaml
Referencing: [this post on the AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html).
This doesn't seem to work locally when doing `sam local start-api` but I'm going to see if that's just a limitation of the local sam cli testing by deploying the new template.
=> attempting to add gzip compression to API responses.

src/store/api.js
Referencing this Issue: https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/153
I changed `buildingFeature` function but not `boundedFeatures` function, as it doesn't seem like we're using `boundedFeatures` yet.
=> switch api to overpass

backend/app/building.js, backend/app/meter.js, backend/dependencies/nodejs/models/compress.js, backend/template.yaml, backend/tests/setupBackendTests.js
This PR also helps to address #123 by reducing the response size returned by the Lambda API for the `/allbuildings` `/data` and `/batchData` routes.
Previous to this PR, allbuildings had a response size of 167kb (167,451 bytes).  With Brotli compression it's 3kb (3341 bytes).
This PR does require shifting these routes from using AWS's REST API calls to using AWS's HTTP API calls (both of them use http, the name difference is just how amazon distinguishes the services) which means we won't have any fancy AWS caching out-of-the-box, but I expect the speed-up from compression will overcome that particular deficiency.
=> Added response compression to data routes

.github/workflows/test-build-s3.yml
Reference Issue: https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/210
The idea is to add `sam validate` to test builds to maybe help catch backend errors before pushing to master. The old Travis file did this. Adding `sam package` to test builds might also help, since the old Travis file did this, but I'm not sure.
=> test s3 sam validate

src/components/navBar.vue
Reference Issue: https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/209
Commented out sign in / out button.
=> comment out sign in / out button

src/components/campaigns/campaign_building_list.vue
Clicking on a building with data (e.g. Poling Hall, as shown below) no longer causes the buildings with no data (Weatherford and ILLC) to randomly switch places. Check in localhost:8080/campaign/9
=> fix sorting nan blocks at the bottom

src/components/navBar.vue, src/store/user.module.js
For some reason it says "My Dashboard" when logged in via some other OSU app, e.g. with Carbon Calculator. Since we haven't / don't plan to implement admin interface on energy dashboard, we should remove this. I commented out for now.
It also says something about "views" in console, probably also related to login. I commented out for now.
=> [PR] Remove views console error and also My Dashboard from navbar

src/components/campaigns/campaign_list.vue
If campaign starts with word "test", then it's only shown on localhost:8080.
This saves the effort of actually toggling the campaign name in MySQL workbench.
Tested to work on the test s3 build: http://energy-dashboard.s3-website-us-west-2.amazonaws.com/#/campaigns
If in the future there is interest in also showing hidden buildings on localhost, we can change the `if (!state[key].hidden)`  statements at [line 171](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/map.module.js#L171) and also [line 182](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/map.module.js#L182) of `src/store/map.module.js` to check for `process.env.VUE_APP_HOST_ADDRESS`.
At present I think this is unnecessary, it isn't too hard to query the …
=> see if this shows test campaign only on local

src/components/view/card.vue
Fix the Edit buttons for non-solar buildings (forgot to surround list of solar buildings with parenthethes).
=> fix non solar edit buttons

src/components/charts/chartController.vue, src/components/view/card.vue
- I recently noticed that only 35th array has correct card dimensions and attribution at the bottom. I realized this is because my v-if statement was not configured correctly.
- Have fixed so all 4 Tesla solar buildings are styled the same now with same dimensions of cards and attribution
- Linked to the OSU article about OSU / Tesla Partnership
- ![image](https://github.com/OSU-Sustainability-Office/energy-dashboard/assets/82061589/4a3d3349-cef2-4f6b-ade9-435fbce940df)
- Tested locally
- Tested in Test S3 Bucket (e.g. http://energy-dashboard.s3-website-us-west-2.amazonaws.com/#/building/36/2)
=> [PR] Fix Iframes Path and Improve Attribution

.env.development, .github/workflows/gh-deploy.yml, .github/workflows/test-build-s3.yml, backend/template.yaml, package.json
hopefully works as intended
node16 end of life is coming up in AWS Lambda - https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
=> [PR] Node 18 Upgrade

.env.development, src/components/extras/heropicture.vue, src/components/map/map_compareside.vue, src/components/map/map_prompt.vue, src/components/view/view.vue
The comparison graphs didn't display correctly before, now they do.
Fixed background colors on comparison map popup, and slanted background pictures for the building comparison pages
=> [PR] Fix comparison graphs

.env.development, src/components/building_list/building_list.vue, src/components/map/map.vue
Styling needs a bit more work
It is radio buttons (select one energy type deselects all others, except if you click "All", in which case all energy types are shown)
If checkboxes are desired, can switch to checkbox
Need to add "Operations" building type later
=> [PR] Energy Filters Frontend Revamp

src/components/map/map.vue, src/components/map/map_prompt.vue
Fixes for Compare tool:
- selecting non-electric buildings now triggers error component correctly, regardless of order in selecting buildings
- buildings with some but not all non-electric data are now compatible with compare tool
- markers no longer become un-removable if you click "cancel" on compare tool before removing markers
- can now add buildings to comparison array from building menu search bar
- clearing search input now removes tooltips from search
=> [PR] comparison menu misc bug fixes

src/components/view/navdir.vue, src/components/view/view.vue
Didn't mean to remove access to download feature.
Revert changes to `src\components\view\view.vue` and `src\components\view\navdir.vue` from [this commit](https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/262/files#diff-2d67f7e52957225657f3c06be6ebce5b1c03a7331744ad94a66a6eed818f9e9e)
=> [PR] add back download button

src/components/map/map.vue
Set building_compare_error to false in two places so that the modal will close if a building is clicked on or a new comparison is started.
=> Fix comparison menu cancel bug

src/components/map/map.vue
Used buildings getter to pull building name from database instead of from Openstreetmap. This fixed the Arnold Cafeteria vs Arnold Dining Hall issue, as well as removed the need for hardcoding 'OSU Operations' building name.
=> Fixed map name discrepancy

src/components/map/map.vue
Clicking on the "Compare in FullScreen" dropdown when a non-electricity building is selected causes various issues. 
Comparing in FullScreen when only one non-electricity building is selected or two non-electricity buildings are selected
---
It gets stuck on a blank page with type errors in the console
Comparing in FullScreen when a non-electricity and an electricity building are selected
---
If the non-eletricity building is clicked first, it does the same as above, but if the electricity building is selected first, it tries to compare them but can't bring up a chart for the non-electricity building
Code
---
Moving only lines 367 - 371 above the if-statement fixed it only when the non-electricity building was selected first, but moving the updateModifier logic above fixed the issue when …
=> Fixed FullScreen comparison bug

src/components/map/map.vue
GeoJson issue: https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/274
- Basically if you just click "All" and then "Electric" (alternate between them, do this like 4 times each), you get a console error eventually
Map Search: https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/288
- I didn't notice this issue back when I reviewed a PR for it, so that's my bad
=> [PR] fix map search and geojson

src/components/view/modals/edit_card.vue
There was a typo in two places that was throwing an error in the console whenever you switch the Meter type (from steam to electricity for example). In addition to that, it was defaulting the Measurement to a value that would cause issues if the user just hit "ok" instead of changing the value to a valid one. 
Fixing the typo `form[currentIndex].point = null` to `form.sets[currentIndex].point = null` would clear the Measurement input completely after switching the Meter type, but this would not throw any errors and would still allow the user to hit "ok" and try to send the request, which would fail. 
I changed it so that when the Meter type is changed, the Measurement is set to whatever the first Measurement type is for that Meter type. The measurement can still be changed with the …
=> Fixed Meter change issue

src/components/extras/contact.vue, src/components/get_started/faq.vue
=> Changed contact info from email to OSU fa contact page

backend/dependencies/nodejs/meter_classes.js
basically [this part of dependencies/nodejs/meter.js file](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/backend/dependencies/nodejs/models/meter.js#L112) bugs out if it can't find the meter class, and allBuildings API call calls all the meters connected to a meter group connected to a building, so that was why allBuildings API call was timing out on prod earlier today.
So I just move meter class changes from https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/302 into prod for now.
Another approach would be to buildings with "hidden" attribute from the allBuildings API call
(e.g. https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/backend/dependencies/nodejs/models/building.js#L225), but I don't know if that would make it …
=> Push Meter Class Changes to Prod

src/store/meter_group.module.js
It seems that by the time PacificPower meters get to meter_group.js file, they are accumulated_real measurement type anyways.
However, it could be good to handle case for solar meters in the future regardless.
Other notes for adding multiple meters to Radiation Center meter group:
(This may be a good indication of future potential issues of supporting multiple-meter meter groups with solar energy type, since PacificPower uses energy_change initially)
- Measurement type is accumulated_real by the time it reaches src/store/meter_group.js, so multiple meters can be combined into one meter group for PacificPower meters without any issue
- Adding up accumulated_real values for various days seemed to sum up values from 3 meters as expected, and Inspect Element > Network makes 3 API calls at …
=> Handle multiple meters per meter group for Solar

.env.development, src/components/charts/chartController.vue, src/components/charts/linechart.js, src/components/map/sideView.vue
Hourly/15-minute Interval Before
---
Both hourly and 15-minute intervals would only display the day on the x-axis
Hourly/15-minute Interval After
---
The new hourly interval is displayed in the bottom picture. 
The 15-minute interval displayed in the top picture now shows the day of the week and the time, which is every 30-minutes here due to having ~2 1/2 days of data displayed. I added formatting to the 'minute' option so that the day is visible, otherwise the data is hard to read as displayed here, without the update:
Monthly Interval
---
One side effect of this change is that the monthly interval labels are now `Month Year` instead of `Month / Day`:
Before:
After:
This can easily be changed by adding a formatting rule for the month interval if the previous format is preferred.
=> Fix x-axis ticks to reflect hourly and 15-minute intervals

src/components/charts/chartController.vue
- Issue was that the charts for this view do not have a "multStart", so it was trying to read an undefined value
=> fixed bar chart not loading for campaign single building view

src/store/chart_modifiers/line_bar/baseline_perc.js
- https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/318
- Poling Hall (as of April 22, 2024) shows percentages of 400 or 500% energy savings (implausibly high), as shown below
- This is related to [this old PR](https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/216/files) from last year
- The objective of that PR was to try to fix Weatherford from the 2022 campaign to show up, which might also lead to the possibility of supporting manually uploading data for a particular building in a campaign (the original issue with Weatherford was that because the data was manually uploaded in SQL, the data was only uploaded in hourly increments while the database expected 15 minute values)
- However, the findClosest function (at least in `baseline_perc.js` file) is …
=> poling campaign fix

backend/dependencies/nodejs/models/meter.js
- Closes https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/320
- Fixed the "tesla meter check" to check from a fixed list of Tesla meters (given that we do not expect any new Tesla meters to be added), instead of checking for first letter "M"
- Issue was that Merryfield Hall (not Tesla) has a meter name starts with "M", triggering the Tesla logic by accident
- A better long term fix (maybe for another PR) is to figure out how to get the Tesla meter IFrames to display correctly without having to send an API call to Energy Dashboard Database
- Setting meter_group ID to `null` causes the Tesla meter Iframes to disappear currently, so I assume that the "card" component (`src\components\view\card.vue`), which wraps around the charts on the building / map pages, checks meter …
=> Fix Merryfield

.env.development, backend/app/pacific_power_exclusion.js, backend/dependencies/nodejs/models/pacific_power_exclusion.js, backend/template.yaml
Added an endpoint to retrieve all Pacific Power Meters in the `pacific_power_exclusion` table of the database. 
See also:
https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/313
https://github.com/OSU-Sustainability-Office/automated-jobs/issues/47
Testing
---
* Run backend locally (`sam local start-api` from backend directory)
* Visit http://http://localhost:3000/ppexclude
* There are only two meters in the database for now, one to be excluded and one to be included
TODO
---
* Update PacificPower scraper in automated-jobs repo to retrieve exclusion list and use it to decide whether or not to upload data for each meter
* If a meter is not on the exclusion list, that means it's a new meter, update scraper to add meter with `exclude` field of `new`
* Add endpoint for adding …
=> Pacific Power exclusion endpoint

backend/dependencies/nodejs/models/pacific_power_recent.js
For some reason the last data shown on ppRecent API endpoint (on master branch) was from May 4th instead of 3rd as expected, leading to errors:
Pretty sure it's related to timezone (between 5 pm (4 pm during daylight savings) to 11:59 pm pst, the 7th day might be off by a day).
Not that it matters for the production version of webscraper running on AWS ECS, as it's running on a cron job at the same time of day, but this could help a lot for debug / local dev.
Copied function over from the timezone checking function we use for automated-jobs/SEC/readSEC.js etc.
Quick demo for testing: https://playcode.io/1866567
=> 7th day timezone hotfix?

src/components/get_started/buildingListTab.vue, src/components/get_started/mainDescription.vue, src/components/navBar.vue
- Closes https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/297
- Removed `margin-left: -10px` and `margin-right: -10px` from navbar component, which was what caused the bug
- Also shortened "Building List" to just "Buildings", partly because the "Building List" text would render on 2 lines without negative margins (on mobile device resolutions, like 600px wide screen), and partly because it's not like we show "Campaign List" instead of "Campaigns
- Also replaced "Building List" with "Buildings" in the FAQ ("getting started") tab
- Actual component names or code comments referencing "building list" were not changed
=> fix firefox active tab highlight bug

.env.development, src/components/view/modals/download_data.vue, src/components/view/modals/edit_card.vue, src/components/view/view.vue, src/store/block.module.js
- https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/305
- Forgot to make an issue for the week label capitalization but should be self explanatory (`1 week` > `1 Week`)
- Solar building (not tesla): http://localhost:8080/#/building/42/2
- Solar building (tesla): http://localhost:8080/#/building/35/2
=> fix solar / pp timeframe override and week label capitalization

.github/workflows/API-deploy.yml, .github/workflows/gh-deploy.yml, .github/workflows/test-build-s3.yml
All of the workflows have warnings that Node.js 16 actions are deprecated and need to use Node.js 20.
=> Update actions node20

.github/workflows/gh-deploy.yml, .github/workflows/test-build-s3.yml, src/store/chart.module.js
The LINC meter with ID 105 (previously labeled MDS but is now the main LINC meter) was off by a factor of 10. 
Database/Back-end Fix
---
I first tried fixing the data in the DB directing via [this branch](https://github.com/OSU-Sustainability-Office/energy-dashboard/tree/linc-mds-multiplier). Even though all of the data was correctly multiplied by 10 here and in the database from 1/1/2024 to now to test it, something was off with the math on the front-end, causing some stretches of data to look similar to before and some being correct, with huge jumps in between. I'm going to leave the issue open for now and look into this more at a later time.
Front-end Fix
---
This will catch the meter after the accumulation math and check if it's the main LINC meter (meter_group_id 199) and accumulated …
=> Temporary LINC meter fix (front-end)

backend/app/meter.js
This changes the `totalYieldYesterday` value for Solar Meters to `totalYield` since we are going to start checking the past few days for missed uploads. It also checks for duplicate data before uploading to the database. To test it, run the [Ennex branch here](https://github.com/OSU-Sustainability-Office/automated-jobs/pull/84) with the `--local-api` flag after starting up the backend locally. The database should be up to date to today, so feel free to delete one row from the `Solar_Meters` table to test that it will upload non-duplicate data as well.
=> Solar Meter Upload Update

src/components/get_started/mapTab.vue, src/components/map/map.vue
- Remove Dining category
- Remove Athletics & Rec category
- Rename Events & Admin -> Events & Engagement  (Includes Events + Athletics & Rec)
- Rename Operations -> Admin & Operations  (Includes Admin + Operations)
- Rename Residence -> Residential Life (Includes Residence + Dining)
=> Reorganize and renamed categories

src/App.vue
Per request, I've added a note to the "First Timer" dialog that lets the user know subsequent load times for the map will be faster.
=> Update first-time dialog to have a note about map load time

src/components/charts/chartController.vue, src/components/view/card.vue
One of our five [Tesla Solar Meter Buildings](https://sustainability.oregonstate.edu/ground-mounted-photovoltaic-arrays) was missing from the dashboard. I've added it to the database (currently hidden from production view) and updated the hard-coded values required to show it on the dashboard. For future reference, these are the `INSERT` statements for adding a new Tesla Solar Meter:
Buildings:
*  start out as hidden (value of 1), then change to 0 when finished testing so it shows up in production
```
INSERT INTO buildings (map_id, image, `group`, `name`, hidden)
VALUES (1130766362, "aquatic_animal_health_lab.jpg", "Admin & Operations", "Aquatic Animal Health Lab", 1);
```
Meters: 
* I don't think the name matters for these meters anymore, the existing Tesla meters have what look like …
=> Add Missing Tesla Solar Meter

backend/dependencies/nodejs/models/meter.js, src/store/block.module.js
Previously, Tesla meter data was stored and managed by the energy dashboard. However, we have since switched to using an iFrame to display Tesla data directly from the source. Unfortunately, the legacy logic for retrieving Tesla meter data from our database was never removed. This outdated API call is now generating errors, which in turn trigger false alarms in AWS Cloudwatch. By removing or bypassing this API call for Tesla data, I'm hoping it gets rid of the false alarms.
=> Avoid getData() API calls for tesla meters

src/components/extras/contact.vue
The URL for the Sustainability Website has been updated (as a result of a Drupal update). The dashboard's only reference to the website is for the "Contact" page. This change fixes the broken link and ensures users are directed to the correct website.
=> Update contact url

.github/dependabot.yml
With the Energy Dashboard relying on a high amount of dependencies that are ever-changing, I've updated the dependabot to check for updates within the Docker (Dockerfile) + NPM (package.json) environments.
=> Add npm/docker version updates to dependabot

.env.development, .github/dependabot.yml, backend/app/meter.js, backend/dependencies/nodejs/models/meter.js, package-lock.json, package.json, src/components/building_list/building_list.vue, src/components/charts/linechart.vue, src/components/map/map.vue, src/components/view/modals/download_data.vue, src/components/view/modals/edit_card.vue, src/main.js, src/store/block_modifiers/campaign_linebar.mod.js, src/store/chart_modifiers/line_bar/accumulated_real.js, src/store/chart_modifiers/line_bar/avg_accumulated_real.js, src/store/chart_modifiers/line_bar/baseline_perc.js, src/store/chart_modifiers/line_bar/baseline_perc_total.js, src/store/chart_modifiers/line_bar/default.js, tests/unit/components/building_list.spec.js
- Updated eslint-plugin-node to latest version
- Removed Vue-i18n (unused)
- Resolved ESLint’s vue/no-reserved-component-names rule
- Added dependabot support for backend's npm (package.json)
After bumping eslint-plugin-node, all of the ESLint plugins are on the latest versions. The next step would be to upgrade ESLint to version 9 and address the unmaintained eslint-config-standard dependency (which doesn't seem to support to latest versions of ESLint + plugins).
Searching the codebase has shown that Vue-i18n isn't actually used and was likely included as boilerplate. Therefore, I've uninstalled it.
- Upgrade ESLint
- Evaluate eslint-config-standard
=> Update ESLint dependencies and remove Vue-i18n

src/components/campaigns/campaign_building_list.vue
On full-screen for some devices, the Leaderboard for campaigns would have some of the building tabs side-by-side. Some of the tabs also had the bottom outline cut-off from view, as seen in Finley Hall below.
Before
After
=> Fix Campaign Leaderboard Styling

src/components/view/modals/edit_card.vue
During a previous ESLint upgrade, nesting a <span> inside a <template> was suggested, but it broke functionality. This reverts that change to restore proper behavior.
=> Revert edit modal change

.env.development, src/components/campaigns/campaign_building_list.vue, src/components/campaigns/main_campaign_view.vue, src/components/map/sideView.vue, src/components/map/time_switch_buttons_big.vue, src/store/campaigns.module.js, src/store/chart_modifiers/index.js, src/store/chart_modifiers/line_bar/avg_accumulated_real.js, src/store/chart_modifiers/line_bar/baseline_perc_total.js, src/store/chart_modifiers/line_bar/baseline_total.js, src/store/chart_modifiers/line_bar/periodic_real.js
- Aquasuite data showing as middle of the data instead of midnight. Fixed by removing offset when loading in campaign start and end dates. Works for users in PST time zone, but needs more testing to see if it'll work elsewhere.
- Leaderboard refreshing is completely fixed by reverting the forceKey removal and modifying block logic to trigger a refresh
- Aquasuite meters showing future data was fixed by adding more robust conditionals
- PPM had unrelated campaign bug that was fixed
- Ensure campaigns work for all time zones
- Remaining bug: PPMs show data for April 27th despite the campaign starting on the 28th. I did some testing by removing the current data and the issue persists. There's an underlying assumption that all data is in 15 min intervals due to Aquasuite data so I believe …
=> Fix campaign bugs

src/store/block_modifiers/campaign_linebar.mod.js, src/store/chart.module.js, src/store/chart_modifiers/line_bar/avg_accumulated_real.js, src/store/chart_modifiers/line_bar/baseline_perc.js, src/store/chart_modifiers/line_bar/baseline_perc_total.js, src/store/chart_modifiers/line_bar/baseline_total.js, src/store/chart_modifiers/line_bar/periodic_real.js, src/store/meter.module.js, src/store/meter_group.module.js
- Removed 15-minute offset previously subtracted from dateStart to allow PPM charts to show properly. The reason for the original adjustment is unclear, but Aquasuite data appears unaffected after removal. Could be worth looking through Git Blame.
- Implemented monthly bucketing for periodic_real data (PPM + Solar Meter). Buckets start at midnight PST for consistency across campaigns. This can easily be modified to 11:59 PM in the future if needed.
- Updated PPM baseline logic to match Aquasuite’s: it now averages daily kWh usage by day of week (e.g., all Mondays in the comparison period).
- PPM data is stored as 11:59 PM PST, but campaign charts start at midnight PST, causing the first day’s data to be excluded.
- As a workaround, dateStart is decremented by 1 second in the request …
=> Fix periodic real data

backend/app/building.js, backend/dependencies/nodejs/models/building.js
API requests must now have a password to update the building's OSM data.
=> Restrict API access for building OSM update

src/store/map.module.js
This is a small patch that compliments PR #403. I overlooked the fact that OSM sometimes returns a node id, which is not what we are looking for. We are looking for the map id.
=> Fix geoJSON backup mechanism logic

backend/package-lock.json, backend/package.json, package-lock.json, package.json
- Bump eslint-plugin-vue from 10.1.0 to 10.2.0
- Bump element-plus from 2.9.11 to 2.10.1 
- Bump vitest from 3.1.4 to 3.2.2 in /backend 
- Bump @vitest/coverage-v8 from 3.1.4 to 3.2.2 in /backend
- Bump sass from 1.89.0 to 1.89.1
- Remove ajv (unused)
=> Bump dependencies

src/components/building_view/modals/DownloadData.vue
The “Download Data” button became unresponsive, even though no recent code changes had been made. Console logs revealed an error occurring during data traversal.
The promises array was populated with functions instead of actual promise values. As a result, Promise.all() attempted to resolve an array of functions, leading to the failure.
The issue was resolved by invoking the async functions before proceeding, ensuring the data was properly formatted and handled as expected.
=> Fixing Download Data Feature

src/components/ui/TimeRangeSwitcher.vue
There was outdated logic in the time range switcher that caused issues with the Solar Panel charts. I believe this logic should have been removed when we updated the date/time format for Solar Panel data and refactored the chart calculations.
I’ve also consolidated the code by introducing a preset map, which replaces the long, confusing chain of if/else statements.
=> Remove outdated solar panel logic. Clean up time range switcher code. 

backend/package-lock.json, backend/package.json
This PR updates a few dependencies/devDependencies to newer versions:
Dependencies
•	dotenv: ^16.5.0 → ^17.2.2
•	fs-extra: ^11.3.0 → ^11.3.2
•	yaml: ^2.7.1 → ^2.8.1
DevDependencies
•	@vitest/coverage-v8: ^3.2.3 → ^3.2.4
•	vitest: ^3.2.3 → ^3.2.4
=> Bump backend npm packages
