- dataCollection/.gitignore
- dataCollection/package-lock.json
- dataCollection/package.json
- dataCollection/server.js
This has been tested with demo XML data from the valleyLibrary. Will have to test on Monday with actual acquisuite data.
> Create NodeJS server for inserting temp data entries into database.

- .gitignore
- README.md
- python/importData.py
- python/tempToPerm.py
Look at this for information on tables and and the algorithm for putting data from temp to perm.
> Added python scripts to pull data from mongo and upload to sql

- dataCollection/compute.js
- dataCollection/server.js
Fixed a ton of bugs with data collection. Specifically, bugs pertaining to arrays vs non arrays when there is one device vs multiple devices reporting.
It's tested and works really well, now.
> Fixed a ton of bugs with data collection.

- dataCollection/create_db.sql
- dataCollection/server.js
Modifies the data collection algorithm so that it is compatible with our new DB schema. I also included a MySQL script for creating another DB, just in case.
> Data collection

- .travis.yml
- backend/app/images.js
- src/components/map/map.vue
- src/components/map/switch_buttons.vue
@broha22 Please briefly look over this. I kept the same size parameter so everything should keep working smoothly.
> Update image GET route with new s3 bucket stuff

- backend/app/now.js
This should hopefully fix the CORS error occurring on the main branch with the system time
> Added Response Class to function

- README.md
Important change, please merge immediately
> Critical Bug Fix

- backend/dependencies/nodejs/meter_classes.js
- backend/dependencies/nodejs/models/building.js
- backend/dependencies/nodejs/models/meter.js
- backend/tests/data_layer.spec.js
- src/store/block.module.js
- src/store/chart.module.js
- src/store/meter_group.module.js
ahh yeah (⌐■_■).
obligatory prayer to the computer gods: please work I need to fix the front-end website which is bricking after I made a small database change
> Add solar panel support to frontend (⌐■_■)

- src/store/chart_modifiers/index.js
- src/store/chart_modifiers/line_bar/energy_change.js
This should make it so the "hour" interval option readings are analogous to the ones present on Solar City.
> added energy_change linebase

- public/sustainability_map/index.html
Ok, now the analytics should work for the sustainability map
> added new token

- src/store/map.module.js
Should help address #123 by reducing the total API requests we send at start-up for building geometry.
On my local machine it reduced the total initial HTTP requests from 34 requests to 11 (since previously we sent 1 request per building).  Reducing the total number of requests doesn't necessarily mean we'll see a large speed-up but it makes sense to batch them in this case given that our map blocks until we get all the building geometry anyway.
> Batched Overpass API requests

- backend/template.yaml
remove node_modules folder for testing maybe, then `npm i`
> Node16 backend

- .env.development
- src/components/charts/chartController.vue
- src/components/view/card.vue
Looking into iframe for Tesla Solar Panels. Conditional rendering based on the `this.path` value in `src/components/charts/chartController.vue`.
> Iframe for Tesla Solar Panels

- .env.development
- backend/dependencies/nodejs/models/meter.js
Closes https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/229
Local Tests:
Checked if both Tesla and SEC solar buildings / graphs show correctly.
I would test it on deployment bucket (http://energy-dashboard.s3-website-us-west-2.amazonaws.com/#/building/35/2), but changes to backend will only take effect if merged into Master branch.
> [PR] seems to fix iframes not showing

- .env.development
- src/components/extras/contact.vue
- src/components/get_started/faq.vue
- src/components/navBar.vue
- src/router/index.js
Updated Navbar / Contact Page
Updated FAQ
> [PR] update faq and contact

- src/components/get_started/faq.vue
Removed questions relating to cost of the dashboard (as we are no longer planning to commercialize this or recommend other universities to use our dashboard as a template IIRC), and also edit the "why we collect data every 15 minutes" question to be more specific according to manager's opinion.
> [PR] remove cost question and edit 15 minutes question

- package-lock.json
- package.json
`npm run prettier` and `npm run lint --fix` all in one command. change brought over from mobile nav branch
> [PR] Add Format Script

- .env.development
- src/components/map/map.vue
Issue - https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/257
> [PR] Add Solar Filter to Map Page

- backend/dependencies/nodejs/meter_classes.js
- backend/dependencies/nodejs/models/meter.js
- src/store/chart.module.js
- src/store/meter_group.module.js
TODO
- remove other measurements other than energy_change / energy produced from solar class (make new class?)
- maybe fix "total solar panel" etc in block.module.js's loadDefault
> update solar label prelim work

- backend/dependencies/nodejs/models/meter.js
- closes https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/263
Solar Endpoint
- http://localhost:3000/data?id=124&startDate=1710718200&endDate=1715903100&point=energy_change&meterClass=9990001
PacificPower Endpoint
- http://localhost:3000/data?id=162&startDate=1710718200&endDate=1715903100&point=accumulated_real&meterClass=9990002
Verify that more recent time_seconds values are on top
- https://github.com/OSU-Sustainability-Office/automated-jobs/issues/51
> Sort solar / pacificpower meter data by time descending (newest on top)

- .env.development
- src/App.vue
- src/components/charts/barchart.vue
- src/components/charts/chartController.vue
- src/components/charts/linechart.vue
- src/components/map/map.vue
There were a couple of bugs and errors after the upgrade. This PR fixes a few of them. Specifically:
Fixes #354, fixes #355, fixes #352
I've also been planning on making the chart child components easier to read. To do this, I broke up the chart options into multiple smaller functions in both the linechart and barchart vue components. No changes were made to the actual code logic. Doing the same for the chartController should also be considered in the future.
> Resolve remaining bugs from Vue3 upgrade 

- src/components/view/card.vue
The URL has been updated to point to the new website.
> Update Tesla info link

- backend/app/building.js
- backend/dependencies/nodejs/models/building.js
- backend/template.yaml
- backend/tests/buildTestDatabase.js
- package-lock.json
- src/components/map/map.vue
- src/store/api.js
- src/store/map.module.js
This PR removes the Energy Dashboard’s dependency on the Overpass API, aiming to improve page load performance and reliability. For a more in-depth explanation, see [Automated Jobs PR #93](https://github.com/OSU-Sustainability-Office/automated-jobs/pull/93). 
As a reference point, I ran the dashboard through GTmetrix to assess its current performance. While this update doesn’t address all bottlenecks, it’s a meaningful step toward a faster and more stable experience.
> Request Building GeoJSON data from AWS Lambda instead of Overpass API

- src/components/map/map.vue
This fixes the [infinite loading](#407) bug when filtering the map via the side menu options.
> Fix infinite loading when filtering map

- backend/dependencies/nodejs/models/meter.js
Fixes broken meter post endpoint as a result of PR #411
> revert accidental delete
